name: Process XML Feeds to CSV

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1,5,9,13,17,21 * * *'
  workflow_dispatch:

jobs:
  process-feeds:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run processing script
        run: |
          python process_urls_to_csv.py

      - name: List generated CSV files
        run: ls -l *.csv || true # This will not fail the workflow if no files are found.

      - name: Upload processed CSV files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: processed-catalogue-files
          path: "*.csv"
