name: Process XML Feeds to CSV/XML

on:
  push:
    branches:
      - main
  schedule:
    # Runs every 4 hours, adjusted for Estonian time (EEST, UTC+3)
    - cron: '0 1,5,9,13,17,21 * * *'
  workflow_dispatch:

jobs:
  process-feeds:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is crucial for the workflow to be able to push files.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run processing script
        run: |
          python process_urls_to_csv.py # Assuming your script is named process_urls_to_csv.py

      - name: List generated files
        run: |
          ls -l *.csv || true
          ls -l *.xml || true # List XML files as well

      - name: Commit generated files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add *.csv *.xml # <<< MODIFIED: Added *.xml here
          # The '|| true' handles the case where there are no new files to commit.
          git commit -m "Generated new CSV and XML files from Teztour feeds" || echo "No new CSV or XML files to commit."
          git push
